### ISSUE TITLE
Incorrect model had been used in LFW Evaluation

### ISSUE THREAD

**Issue by AyushAgrawal25** [mbfaria/ShuffleFaceNet_Pytorch#1]
Path: lfw_eval.py
line: 94
Inside the function, getFeatureFromTorch net should be an instance of the ShuffleFaceNet model, not the MobileFaceNet model.
If I am correct please assign me this issue I want to contribute to this repository.

**Comment by emrectn** [comment]
> Path: lfw_eval.py line: 94 Inside the function, getFeatureFromTorch net should be an instance of the ShuffleFaceNet model, not the MobileFaceNet model. If I am correct please assign me this issue I want to contribute to this repository.

Hi AyushAgrawal how did you fix the bug, could you paste the correct function code in here

**Comment by AyushAgrawal25** [comment]
> > Path: lfw_eval.py line: 94 Inside the function, getFeatureFromTorch net should be an instance of the ShuffleFaceNet model, not the MobileFaceNet model. If I am correct please assign me this issue I want to contribute to this repository.
> 
> Hi AyushAgrawal how did you fix the bug, could you paste the correct function code in here

I am making a PR and I am gonna link it here.
You can check there and if you find it relevant merge it.

**Comment by AyushAgrawal25** [comment]
Please refer to this PR: https://github.com/mbfaria/ShuffleFaceNet_Pytorch/pull/2

I have made the required changes.

**Comment by mbfaria** [comment]
PR [#2](https://github.com/mbfaria/ShuffleFaceNet_Pytorch/pull/2) was merged. 

Thank you, guys!
I had no time to debug and test this code for now, and you guys solved the problem very simply!
